### ISSUE TITLE
Usage and MVP

### ISSUE THREAD

**Issue by josiahbryan** [nickboucher/WebTor#6]
Hey Nick -

I don't care about a general page proxy - but I would like to use this in my own app to route the traffic back to my server anonymously - e.g. protect the user's traffic. I can code the data layer of my app to use WebTor directly, no need for any fancy proxy implementations.  Can you point me at a basic example of making a basic GET or POST using WebTor?

Really simple and totally off the top of my head pseudocode showing what I'm wanting to code: (Google URL used only as an example.)

```
const client = require('webtor');
client.bootstrap() // setup encryption
  .then(() => client.start())
  .then(() => {
     client.get('https://google.com/search?q=webtor').then(data => console.log(data));
  });
```

**Comment by nickboucher** [comment]
Hi Josiah --

Thanks for reaching out! My partners and I never had time to finish implementing WebTor, so there really aren't any good working examples. I'd love to come back and finish the implementation but am a bit pressed for time at the moment. If I remember correctly, we were working on the network bootstrapping process when we jumped to a different project.

I dropped a [formal research paper](https://github.com/nickboucher/WebTor/blob/master/WebTor%20Research%20Paper.pdf) that we wrote into the root of the repository if you would like to take a look. It's not technical documentation with examples, but it will give a better understanding of the model we were implementing and perhaps help you to extract the portions of the codebase that would be beneficial to you.

In the meantime, happy to review pull requests from anyone who would like to contribute to the implenmentation of WebTor!

-Nicholas
